//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Runtime Version:4.0.30319.34014
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solfeggio.Languages {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class English {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal English() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Solfeggio.Languages.English", typeof(English).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Buy.
		/// </summary>
		internal static string Buy {
			get {
				return ResourceManager.GetString("Buy", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Skip.
		/// </summary>
		internal static string Skip {
			get {
				return ResourceManager.GetString("Skip", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Now you use the free version.
		///It doesn&apos;t have any limitations.
		///But if you like, please, rate app and buy for a small fee, it will greatly help to develop.
		///Enjoy!.
		/// </summary>
		internal static string TrialMessage {
			get {
				return ResourceManager.GetString("TrialMessage", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Dear user,
		///thank for download!.
		/// </summary>
		internal static string TrialTitle {
			get {
				return ResourceManager.GetString("TrialTitle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Zoom.
		/// </summary>
		internal static string Zoom {
			get {
				return ResourceManager.GetString("Zoom", resourceCulture);
			}
		}
	}
}
